### ISSUE TITLE
Error on The Time Machine example

### ISSUE THREAD

**Issue by oofmoment420** [lumi-a/sliding-blocks#1]
Using the Compute Solution button on [039] The Time Machine yields the error 'RuntimeError: unreachable executed'

**Comment by lumi-a** [comment]
Thanks for the issue! Can reproduce in the web-app. TL;DR: I guess the app runs out of memory, but I'll publish a patch to make it use less memory at the cost of a little performance.

The [rust-crate](https://github.com/lumi-a/sliding-blocks?tab=readme-ov-file#solver) does solve The Time Machine, but it definitely takes the longest time to solve out of all the example puzzles. It does take fewer moves to solve than some other puzzles, but its search-tree has way higher branching-factor than the others, because:
- The Time Machine has many (8) blocks, all of which are different shapes, so we can't exploit any symmetry among them.
- The Time Machine has a lot of free space, so in every move, we can move a lot of different blocks to a lot of different positions.

Contrast this with e.g. Royal Escape: This takes more than twice the amount of moves to solve, and has 10 blocks, but has way less free space, and has only 3 different shapes of blocks (meaning we can exploit a lot of symmetry). Yet, Royal Escape can be solved in less than a second.

I ran some experiments in which I used a data structure that needs less memory than the [current one](https://github.com/lumi-a/sliding-blocks/blob/a16b18b54b1e94430d110fb16d2bb7ae841325b5/src/lib.rs#L154), and _was_ able to solve the puzzle in the web-app that way. The new, smaller data-structure means that puzzles with a very high degree of shape-symmetry (e.g. the 7 short horizontal pipes in Sliding Pipes) will be a little slower to solve: Benchmarks say something like 24% slower for Sliding Pipes, and it'll be the same for every puzzle that has a block-shape with more than 4 blocks of that block-shape. Thankfully, most puzzles don't have such a shape, and those who do automatically have such a high degree of symmetry that they're fast to solve, anyway.

Thanks again for the issue!
